"""Ajout du champ book_image_url

Revision ID: 1cf276793857
Revises: 
Create Date: 2024-11-01 18:48:22.196883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf276793857'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('B')  # Supprimer uniquement la table B

    with op.batch_alter_table('Book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_image_url', sa.String(), nullable=True))
        batch_op.alter_column('book_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Book', schema=None) as batch_op:
        batch_op.alter_column('book_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('book_image_url')

    op.create_table('B',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='B_pkey')
    )
    # ### end Alembic commands ###